// UI strings in Swedish (default) and English (SPEC 2). Terminology follows Swedish practice.
export const STRINGS = {
  sv: {
    appTitle: 'KJ värmeförlustberäkning',
    manualMode: 'MANUELLT LÄGE',
    language: 'Språk',
    tabs: { wizard: 'Projekt', drawings: 'Ritningar', floors: 'Våningar', scale: 'Skala', editor: '2D-granskning', gaps: 'Kompletteringar', align: 'Inpassning', constructions: 'Konstruktioner', model3d: '3D', audit: 'Granskning', list: 'Lista', settings: 'Inställningar', command: 'Kommando (exp.)', materials: 'Material' },
    popout: 'Öppna i eget fönster',
    popoutScreen: 'Placera på skärm',
    save: 'Spara projekt', open: 'Öppna projekt', newProject: 'Nytt projekt', undo: 'Ångra', redo: 'Gör om',
    password: 'Lösenord', passwordPrompt: 'Ange lösenordet för API-åtkomst', ok: 'OK', cancel: 'Avbryt', apply: 'Verkställ', close: 'Stäng', delete: 'Ta bort', add: 'Lägg till', edit: 'Ändra', confirm: 'Bekräfta', yes: 'Ja', no: 'Nej', none: 'Ingen',
    wizard: {
      title: 'Projektinställningar', name: 'Projektnamn', ageCategory: 'Ålderskategori', ageHelp: 'Används bara för att sätta standardvärdet för byggnadens lufttäthet n50 (luftläckage genom klimatskalet, infiltration). Värdet kan ändras per rum.', n50: 'n50 (oms/h vid 50 Pa)', outdoorTemp: 'Dimensionerande utetemperatur (°C)', indoorSetpoint: 'Rumstemperatur, standard (°C)', ventilationSystem: 'Ventilationssystem', ftx: 'FTX med värmeåtervinning', exhaust: 'Mekanisk frånluft', natural: 'Självdrag', supplyTemp: 'Tilluftstemperatur (°C)', brief: 'Projektbrief', briefHelp: 'Klistra in projektbriefen (se docs/PROJECT-PREPARATION.md). Den följer med i varje AI-läsning och kan ändras när som helst.', start: 'Spara och gå till ritningar',
    },
    drawings: {
      title: 'Ritningar', upload: 'Ladda upp ritningar (PDF, TIFF, PNG, JPG)', dropHere: 'Släpp filer här eller klicka', files: 'Filer', pages: 'sidor', readAll: 'Läs alla ritningar', readUnread: 'Läs olästa ritningar', reading: 'Läser…', readDone: 'Läsning klar', pending: 'väntar', running: 'pågår', failed: 'fel', done: 'klar', requests: 'AI-förfrågningar', classification: 'Klassning', plan: 'Plan', vertical: 'Vertikal (sektion/fasad)', discipline: 'Disciplin', level: 'Våning', role: 'Roll', roles: { base: 'Bas', 'scale-reference': 'Skalreferens', 'change-patch': 'Ändringspatch', 'cross-check': 'Kontroll', ignore: 'Ignorera' }, partOfFloor: 'Del av våning', crop: 'Beskärning', remove: 'Ta bort ritning', prompts: 'Promptversion', model: 'Modell', origin: 'Ursprung', exchangeFolder: 'Välj utbytesmapp', exchangeFolderHelp: 'Manuellt läge: appen skriver förfrågningar till mappen och hämtar svar automatiskt.', downloadRequest: 'Ladda ner förfrågan', uploadResponse: 'Ladda upp svar', invalidResponse: 'Ogiltigt svar (schemafel), förfrågan väntar fortfarande', noSheets: 'Inga ritningar uppladdade.', textLayer: 'Textlager', tiles: 'rutor', renderingTiles: 'Renderar rutor…', gapList: 'Luckor', unread: 'Ej läst',
    },
    floors: {
      title: 'Våningar', level: 'Nivå', name: 'Namn', aliases: 'Alias', height: 'Våningshöjd (mm)', sheets: 'Ritningar', confirm: 'Bekräfta våningslista', addLevel: 'Lägg till våning', addProposed: 'Skapa våningar från läsningens förslag', reference: 'Referensvåning', aliasHelp: 'Olika ritningsset namnger samma våning olika. Ange alla namn, kommaseparerade.', coldAttic: 'Kall vind ovanför översta våningen', bottom: 'Nederst', top: 'Överst', approved: 'Godkänd', copyTo: 'Kopiera till våningar', copyRange: 't.ex. 3–9', copyDiff: 'Skillnader mot egen läsning', attic: 'Vind', basement: 'Källare',
    },
    scale: {
      title: 'Skala', referenceFloor: 'Referensvåning', propose: 'Förslag', method: 'Metod', label: 'Referens', realLength: 'Verklig längd (mm)', setScale: 'Sätt skala', referenceBar: 'Dra ankarna till två kända punkter och ange avståndet.', dimension: 'måttsatt sträcka', scaleBar: 'skalstock', typed: 'inskrivet avstånd', referenceWalls: 'Referensväggar', why: 'Varför', pickOther: 'Välj andra', correction: 'Korrektion', applied: 'tillämpad', flagged: 'flaggad', noneNeeded: 'ingen', stamp: 'Skalstämpel', stampCheck: 'Kontroll mot skalstämpel', manualAlign: 'Manuell inpassning', notFound: 'ej hittad', deviation: 'Avvikelse', verticalCheck: 'Sanitetskontroll vertikala ritningar', sheetAssembly: 'Bladsammansättning', clickSamePoint: 'Klicka samma punkt på båda bladen', lengths: 'Längder',
    },
    align: {
      title: 'Manuell inpassning', moving: 'Rörligt lager', reference: 'Referenslager', opacity: 'Opacitet', tint: 'Färg', pointPairs: 'Punktpar: klicka en punkt på referensen, sedan samma punkt på det rörliga lagret. Två par.', pairsDone: 'par klara', move: 'Flytta', rotate: 'Rotera (°)', scale: 'Skala', scaleX: 'Skala X', scaleY: 'Skala Y', nonUniformWarning: 'VARNING: olika skala i X och Y (sträckt inskanning). Tillämpas aldrig automatiskt.', nudge: 'Piltangenter flyttar', reset: 'Återställ', accept: 'Acceptera inpassning', deviation: 'Avvikelse mot referensvåning', method: 'manuell inpassning', heightRef: 'Höjdreferens (nivålinje)',
    },
    editor: {
      title: '2D-granskning', level: 'Våning', layers: 'Lager', paper: 'Papper', lines: 'Linjer', overlay: 'Vektor', walls: 'Väggar', rooms: 'Rum', openings: 'Öppningar', gaps: 'Luckor', separators: 'Rumsavskiljare', annotations: 'Anteckningar (experimentellt)', tools: 'Verktyg', select: 'Markera', deleteTool: 'Ta bort', separatorTool: 'Rita avskiljare', annotateLine: 'Rita linje', annotateFree: 'Rita frihand', annotateNote: 'Placera anteckning', comment: 'Kommentar till AI', commentPlaceholder: 'T.ex. "det här är inte en vägg" eller "detta är två väggar"', comments: 'Kommentarer (batch per våning)', sendComments: 'Skicka kommentarer och anteckningar för omläsning', wallTypes: 'Väggtyper', thicknessBand: 'Toleransband (mm)', cluster: 'Grupp', assignTo: 'Tilldela', measured: 'uppmätt', openingTypes: 'Fönster-/dörrtyper', roomTypes: 'Rumstyper', confidence: 'Säkerhet', reasoning: 'Motivering', heated: 'Uppvärmt', name: 'Namn', roomType: 'Rumstyp', underground: 'Andel under mark (%)', outsideSpace: 'Gränsar mot utrymme utanför projektet', outsideTemp: 'Temperatur i utrymmet (°C)', resolveGap: 'Lucka', gapOpening: 'Öppning', gapArtifact: 'Artefakt (stängd)', gapUncertain: 'Osäker', approve: 'Godkänn våningen', reread: 'Omläsning / nytt underlag', jumpVertical: 'Visa i vertikal ritning', origin: 'Ursprung', origins: { machine: 'maskinläsning', regional: 'AI-omläsning på kommentar', command: 'kommandofönster', user: 'användare' }, clusterColors: 'Färgkodning', highlightSlivers: 'Visa absorberade remsor', snapTol: 'Snapptolerans', cleanupLog: 'Städlogg', changed: 'ändrad', flaggedReview: 'Flaggad för granskning', width: 'Bredd', height: 'Höjd', sill: 'Bröstning', source: 'Källa', apartmentCheck: 'Lägenhetsytor (kontroll)', areaSum: 'Summa rumsareor', printed: 'utskriven area', dangling: 'lösa väggändar', doorHeightGroup: 'Höjd per grupp',
      rereadDialog: { title: 'Omläsning / nytt underlag', swap: 'Byt bara underlag: ny bild ersätter bakgrunden, skalas automatiskt till befintlig geometri. Inget läses om.', keep: 'Läs om, behåll mina ändringar: objekt med mänsklig eller AI-korrigerad märkning återställs över resultatet.', discard: 'Läs om, kasta mina ändringar: ren omläsning.', unmatched: 'Objekt som inte kunde matchas mot nytt objekt', file: 'Ny underlagsfil' },
    },
    gaps: {
      title: 'Kompletteringar', intro: 'Bara det som blockerar 3D eller beräkningen frågas efter.', floorHeights: 'Våningshöjder', floorOrder: 'Våningsordning', underground: 'Andel under mark', attic: 'Finns kall vind ovanför översta våningen?', openingHeights: 'Öppningshöjder per grupp', coverage: 'Täckning: delar av våning som ingen ritning täcker', nothing: 'Inget att komplettera.', continue: 'Fortsätt',
    },
    constructions: {
      title: 'Konstruktioner och ventilation', materials: 'Material', lambda: 'λ (W/mK)', source: 'Källa', verified: 'verifierad', unverified: 'ej verifierad', libraryStatus: 'Bibliotekstatus', constructions: 'Konstruktioner', layers: 'Skikt', thickness: 'Tjocklek (mm)', material: 'Material', uDirect: 'U-värde direkt (W/m²K)', uValue: 'U-värde', chain: 'Spårbarhetskedja', wallTypes: 'Väggtyper', floorTypes: 'Bjälklagstyper', roofTypes: 'Taktyper', slabType: 'Platta på mark', openingTypes: 'Fönster/dörrtyper', assign: 'Konstruktion', inUse: 'används', cannotDelete: 'Används och kan inte tas bort, bara ändras', ventilation: 'Ventilation', baseFlow: 'Grundflöde (l/s per m²)', bulkByType: 'Sätt flöde per rumstyp', flow: 'Flöde (l/s)', apply: 'Tillämpa', infiltration: 'Infiltration (oms/h)', addMaterial: 'Lägg till material (tillverkardata)', addConstruction: 'Ny konstruktion', addType: 'Ny typ', direction: 'Riktning', up: 'uppåt', horizontal: 'horisontellt', down: 'nedåt', defaultFloorNote: 'Alla bjälklag mellan våningar får en bjälklagstyp; översta bjälklaget under kall vind får en egen.', toGround: 'mot mark', pieces: 'Bjälklagsdelar', assignPiece: 'Tilldela bjälklagstyp', exportLibrary: 'Exportera materialbibliotek', importLibrary: 'Importera materialbibliotek', proceed3d: 'Generera 3D',
    },
    model3d: { title: '3D-modell', regenerate: 'Generera om från 2D', rooms: 'Rum', slabThickness: 'Visningstjocklek bjälklag (mm)', legend: 'Klicka på rummets kula för rumspanelen', pending: 'Godkänn våningarna i 2D först' },
    audit: {
      title: 'Granskning', room: 'Rum', unread: 'oläst del av våningen (antas uppvärmd)', total: 'Totalt (W)', transmission: 'Transmission', ventilation: 'Ventilation', infiltration: 'Infiltration', surcharge: 'Köldbryggepåslag', perSurface: 'Per yta', element: 'Element', watts: 'W', area: 'm²', dT: 'ΔT', unheatedTemp: 'Löst temperatur (ouppvärmt)', setpoint: 'Börvärde (°C)', flow: 'Ventilationsflöde (l/s)', supplyTemp: 'Tilluftstemperatur (°C)', ach: 'Infiltration (oms/h)', comment: 'Kommentar', bulk: 'Massredigera', selectByType: 'Välj rum efter typ', freehand: 'Frihandsval i 3D', selected: 'valda rum', applyToSelected: 'Ändra för valda', building: 'Byggnad', perLevel: 'Per våning', heatedOnly: 'Summor över uppvärmda rum', slabCheck: 'Platta på mark: kontroll mot EN ISO 13370', perRoomSlab: 'Summa per rum (två zoner)', isoTotal: 'ISO 13370 byggnadstotal', noWarning: 'Ingen automatisk varning: bedöm skillnaden och justera zontemperaturerna vid behov.', list: 'Rumslista', notEditable: 'Geometri, väggtyper och U-värden ändras i 2D och under Konstruktioner.', other: 'andra sidan', overrideFlag: 'Överföring efter omgenerering, granska', lossFlow: 'flöde till', gain: 'vinst', outside: 'ute', soil: 'mark', slabBand: 'platta, randzon', slabInner: 'platta, inre zon', outsideSpace: 'utrymme utanför projektet', roof: 'tak', coldAttic: 'kall vind (uteluft)', fakeFloor: 'fiktivt bjälklag', wall: 'vägg', window: 'fönster', door: 'dörr', floor: 'golv', ceiling: 'tak/bjälklag', trace: 'Kedja', chainMaterial: 'material', chainConstruction: 'konstruktion', chainType: 'typ',
    },
    settings: {
      title: 'Inställningar', building: 'Byggnadskonfiguration', shielding: 'Skärmningsklass (EN 12831)', shieldingNone: 'ingen', shieldingModerate: 'måttlig', shieldingHeavy: 'kraftig', fakeFloorU: 'U-värde fiktivt bjälklag (W/m²K)', sliverWidth: 'Remsa: minsta bredd (mm)', sliverArea: 'Remsa: minsta area (m²)', baseFlow: 'Grundventilationsflöde (l/s per m²)', soilTemp: 'Marktemperatur väggar under mark (°C)', bandTemp: 'Platta: randzon (°C)', innerTemp: 'Platta: inre zon (°C)', bandWidth: 'Platta: randzonens bredd (m)', soilLambda: 'Markens värmekonduktivitet (W/mK)', tb: 'Köldbryggepåslag (%)', snap: 'Snapptolerans, åsidosätt (mm)', doorRange: 'Dörrhöjd, rimlighetsintervall (m)', scaleNo: 'Skala: ingen korrektion under (%)', scaleAgree: 'Skala: auto-korrektion om avvikelse mellan väggarna under (%)', ai: 'AI-inställningar', modelFor: 'Modell för', jobs: { read: 'första läsning (översikt och rutor)', combined: 'sammanslagning per våning', fullFloorReread: 'omläsning av hel våning', regional: 'regional omläsning på kommentar', annotation: 'anteckningar', command: 'kommandofönster' }, targetRes: 'Målupplösning (mm per pixel)', overlap: 'Överlapp mellan rutor (m)', tileMax: 'Max långsida per ruta (px)', manual: 'Manuellt läge (utvecklarinställning)', workerUrl: 'Worker-URL', scaleTruth: 'Skala: referensväggar', wallBand: 'Väggtjocklek: toleransband (mm)', openingBand: 'Öppningar: toleransband (mm)', ageDefaults: 'n50 per ålderskategori', sources: 'Källor för konstanter', promptVersions: 'Promptversioner', clearPassword: 'Glöm lösenord', imageLimitNote: 'Bildgräns hos modellen vid byggtillfället: 2576 px långsida, 4784 bildtoken (28 px per token).',
    },
    command: { title: 'Kommandofönster (experimentellt)', intro: 'Skriv en projektomfattande ändring. Vid tveksamhet frågar AI:n innan något ändras. Inget ändras förrän du klickar Verkställ.', placeholder: 'T.ex. "ändra marktemperaturen till 5 °C i hela projektet"', send: 'Skicka', question: 'Fråga tillbaka', proposal: 'Föreslagna ändringar', applied: 'Genomförda ändringar (ett ångra-steg)', freeText: 'Fritt svar', history: 'Historik' },
    status: { saved: 'Sparat', restored: 'Projekt återställt från webbläsaren', calc: 'Beräknat', error: 'Fel' },
    roomTypes: { living: 'Vardagsrum', bedroom: 'Sovrum', kitchen: 'Kök', bathroom: 'Badrum', wc: 'WC', hall: 'Hall/tambur', storage: 'Förråd', stairwell: 'Trapphus', laundry: 'Tvättstuga', office: 'Kontor', shop: 'Butik/lokal', garage: 'Garage', loggia: 'Loggia', corridor: 'Korridor', technical: 'Teknik', other: 'Övrigt' },
    units: { mm: 'mm', m: 'm', m2: 'm²', W: 'W', C: '°C' },
  },
  en: {
    appTitle: 'KJ heat loss calculation',
    manualMode: 'MANUAL MODE',
    language: 'Language',
    tabs: { wizard: 'Project', drawings: 'Drawings', floors: 'Floors', scale: 'Scale', editor: '2D review', gaps: 'Gap dialog', align: 'Alignment', constructions: 'Constructions', model3d: '3D', audit: 'Audit', list: 'List', settings: 'Settings', command: 'Command (exp.)', materials: 'Materials' },
    popout: 'Open in own window',
    popoutScreen: 'Place on screen',
    save: 'Save project', open: 'Open project', newProject: 'New project', undo: 'Undo', redo: 'Redo',
    password: 'Password', passwordPrompt: 'Enter the password for API access', ok: 'OK', cancel: 'Cancel', apply: 'Apply', close: 'Close', delete: 'Delete', add: 'Add', edit: 'Edit', confirm: 'Confirm', yes: 'Yes', no: 'No', none: 'None',
    wizard: {
      title: 'Project setup', name: 'Project name', ageCategory: 'Age category', ageHelp: 'Used only to set the default air tightness n50 (air leakage through the building envelope, infiltration). It can be overridden per room.', n50: 'n50 (ach at 50 Pa)', outdoorTemp: 'Outdoor design temperature (°C)', indoorSetpoint: 'Default indoor setpoint (°C)', ventilationSystem: 'Ventilation system', ftx: 'FTX with heat recovery', exhaust: 'Mechanical exhaust', natural: 'Natural', supplyTemp: 'Supply air temperature (°C)', brief: 'Project brief', briefHelp: 'Paste the project brief (see docs/PROJECT-PREPARATION.md). It goes into every AI read and can be edited at any time.', start: 'Save and go to drawings',
    },
    drawings: {
      title: 'Drawings', upload: 'Upload drawings (PDF, TIFF, PNG, JPG)', dropHere: 'Drop files here or click', files: 'Files', pages: 'pages', readAll: 'Read all drawings', readUnread: 'Read unread drawings', reading: 'Reading…', readDone: 'Read complete', pending: 'pending', running: 'running', failed: 'failed', done: 'done', requests: 'AI requests', classification: 'Classification', plan: 'Plan', vertical: 'Vertical (section/elevation)', discipline: 'Discipline', level: 'Floor', role: 'Role', roles: { base: 'Base', 'scale-reference': 'Scale reference', 'change-patch': 'Change patch', 'cross-check': 'Cross-check', ignore: 'Ignore' }, partOfFloor: 'Part of floor', crop: 'Crop', remove: 'Remove drawing', prompts: 'Prompt version', model: 'Model', origin: 'Origin', exchangeFolder: 'Choose exchange folder', exchangeFolderHelp: 'Manual mode: the app writes requests to the folder and picks up responses automatically.', downloadRequest: 'Download request', uploadResponse: 'Upload response', invalidResponse: 'Invalid response (schema error); the request stays pending', noSheets: 'No drawings uploaded.', textLayer: 'Text layer', tiles: 'tiles', renderingTiles: 'Rendering tiles…', gapList: 'Gap list', unread: 'Not read',
    },
    floors: {
      title: 'Floors', level: 'Level', name: 'Name', aliases: 'Aliases', height: 'Floor-to-floor height (mm)', sheets: 'Drawings', confirm: 'Confirm floor list', addLevel: 'Add floor', addProposed: 'Create floors from the read proposals', reference: 'Reference floor', aliasHelp: 'Drawing sets name the same floor differently. Enter all names, comma separated.', coldAttic: 'Cold attic above the top floor', bottom: 'Bottom', top: 'Top', approved: 'Approved', copyTo: 'Apply to floors', copyRange: 'e.g. 3–9', copyDiff: 'Differences against own read', attic: 'Attic', basement: 'Basement',
    },
    scale: {
      title: 'Scale', referenceFloor: 'Reference floor', propose: 'Proposal', method: 'Method', label: 'Reference', realLength: 'Real length (mm)', setScale: 'Set scale', referenceBar: 'Drag the anchors to two known points and type the distance.', dimension: 'written dimension', scaleBar: 'scale bar', typed: 'typed distance', referenceWalls: 'Reference walls', why: 'Why', pickOther: 'Pick others', correction: 'Correction', applied: 'applied', flagged: 'flagged', noneNeeded: 'none', stamp: 'Scale stamp', stampCheck: 'Check against scale stamp', manualAlign: 'Manual alignment', notFound: 'not found', deviation: 'Deviation', verticalCheck: 'Vertical drawing sanity checks', sheetAssembly: 'Sheet assembly', clickSamePoint: 'Click the same point on both sheets', lengths: 'Lengths',
    },
    align: {
      title: 'Manual alignment', moving: 'Moving layer', reference: 'Reference layer', opacity: 'Opacity', tint: 'Tint', pointPairs: 'Point pairs: click a point on the reference, then the same point on the moving layer. Two pairs.', pairsDone: 'pairs done', move: 'Move', rotate: 'Rotate (°)', scale: 'Scale', scaleX: 'Scale X', scaleY: 'Scale Y', nonUniformWarning: 'WARNING: different scale in X and Y (stretched scan). Never applied automatically.', nudge: 'Arrow keys nudge', reset: 'Reset', accept: 'Accept alignment', deviation: 'Deviation against reference floor', method: 'manual alignment', heightRef: 'Height reference (level line)',
    },
    editor: {
      title: '2D review', level: 'Floor', layers: 'Layers', paper: 'Paper', lines: 'Lines', overlay: 'Vector', walls: 'Walls', rooms: 'Rooms', openings: 'Openings', gaps: 'Gaps', separators: 'Virtual separators', annotations: 'Annotations (experimental)', tools: 'Tools', select: 'Select', deleteTool: 'Delete', separatorTool: 'Draw separator', annotateLine: 'Draw line', annotateFree: 'Draw freehand', annotateNote: 'Place note', comment: 'Comment to the AI', commentPlaceholder: 'e.g. "this is not a wall" or "these are two walls"', comments: 'Comments (batched per floor)', sendComments: 'Send comments and annotations for re-read', wallTypes: 'Wall types', thicknessBand: 'Tolerance band (mm)', cluster: 'Cluster', assignTo: 'Assign', measured: 'measured', openingTypes: 'Window/door types', roomTypes: 'Room types', confidence: 'Confidence', reasoning: 'Reasoning', heated: 'Heated', name: 'Name', roomType: 'Room type', underground: 'Percent underground (%)', outsideSpace: 'Borders a space outside the project', outsideTemp: 'Temperature of that space (°C)', resolveGap: 'Gap', gapOpening: 'Opening', gapArtifact: 'Artifact (closed)', gapUncertain: 'Uncertain', approve: 'Approve floor', reread: 'Re-read / new underlay', jumpVertical: 'Show in vertical drawing', origin: 'Origin', origins: { machine: 'machine read', regional: 'AI re-read on comment', command: 'command window', user: 'user' }, clusterColors: 'Colour coding', highlightSlivers: 'Highlight absorbed slivers', snapTol: 'Snap tolerance', cleanupLog: 'Cleanup log', changed: 'changed', flaggedReview: 'Flagged for review', width: 'Width', height: 'Height', sill: 'Sill', source: 'Source', apartmentCheck: 'Apartment areas (check)', areaSum: 'Sum of room areas', printed: 'printed area', dangling: 'dangling wall ends', doorHeightGroup: 'Height per group',
      rereadDialog: { title: 'Re-read / new underlay', swap: 'Swap underlay only: the new image replaces the backdrop and is auto-rescaled to the existing geometry. Nothing is re-read.', keep: 'Re-read, keep my edits: objects with a human or AI-corrected tag are restored over the new result.', discard: 'Re-read, discard my edits: clean re-read.', unmatched: 'Objects that could not be matched to a new object', file: 'New underlay file' },
    },
    gaps: {
      title: 'Gap dialog', intro: 'Only what blocks 3D or the calculation is asked.', floorHeights: 'Floor heights', floorOrder: 'Floor order', underground: 'Underground percentage', attic: 'Is there a cold attic above the top floor?', openingHeights: 'Opening heights per group', coverage: 'Coverage: parts of a floor no drawing covers', nothing: 'Nothing to fill in.', continue: 'Continue',
    },
    constructions: {
      title: 'Constructions and ventilation', materials: 'Materials', lambda: 'λ (W/mK)', source: 'Source', verified: 'verified', unverified: 'unverified', libraryStatus: 'Library status', constructions: 'Constructions', layers: 'Layers', thickness: 'Thickness (mm)', material: 'Material', uDirect: 'U-value entered directly (W/m²K)', uValue: 'U-value', chain: 'Traceability chain', wallTypes: 'Wall types', floorTypes: 'Floor types', roofTypes: 'Roof types', slabType: 'Ground slab', openingTypes: 'Window/door types', assign: 'Construction', inUse: 'in use', cannotDelete: 'In use: cannot be deleted, only changed', ventilation: 'Ventilation', baseFlow: 'Base flow (l/s per m²)', bulkByType: 'Set flow by room type', flow: 'Flow (l/s)', apply: 'Apply', infiltration: 'Infiltration (ach)', addMaterial: 'Add material (manufacturer data)', addConstruction: 'New construction', addType: 'New type', direction: 'Direction', up: 'up', horizontal: 'horizontal', down: 'down', defaultFloorNote: 'All pieces between storeys get one floor type; the top-floor ceiling below a cold attic gets its own.', toGround: 'to ground', pieces: 'Floor/ceiling pieces', assignPiece: 'Assign floor type', exportLibrary: 'Export material library', importLibrary: 'Import material library', proceed3d: 'Generate 3D',
    },
    model3d: { title: '3D model', regenerate: 'Regenerate from 2D', rooms: 'Rooms', slabThickness: 'Slab display thickness (mm)', legend: 'Click a room orb for the room panel', pending: 'Approve the floors in 2D first' },
    audit: {
      title: 'Audit', room: 'Room', unread: 'unread part of the floor (assumed heated)', total: 'Total (W)', transmission: 'Transmission', ventilation: 'Ventilation', infiltration: 'Infiltration', surcharge: 'Thermal bridge surcharge', perSurface: 'Per surface', element: 'Element', watts: 'W', area: 'm²', dT: 'ΔT', unheatedTemp: 'Solved temperature (unheated)', setpoint: 'Setpoint (°C)', flow: 'Ventilation flow (l/s)', supplyTemp: 'Supply air temperature (°C)', ach: 'Infiltration (ach)', comment: 'Comment', bulk: 'Bulk edit', selectByType: 'Select rooms by type', freehand: 'Freehand selection in 3D', selected: 'rooms selected', applyToSelected: 'Change for selected', building: 'Building', perLevel: 'Per floor', heatedOnly: 'Totals over heated rooms', slabCheck: 'Ground slab: check against EN ISO 13370', perRoomSlab: 'Sum per room (two zones)', isoTotal: 'ISO 13370 building total', noWarning: 'No automatic warning: judge the difference and adjust the zone temperatures if needed.', list: 'Room list', notEditable: 'Geometry, wall types and U-values are changed in 2D and under Constructions.', other: 'other side', overrideFlag: 'Carried over after regeneration, review', lossFlow: 'flow to', gain: 'gain', outside: 'outside', soil: 'soil', slabBand: 'slab, perimeter band', slabInner: 'slab, inner zone', outsideSpace: 'space outside the project', roof: 'roof', coldAttic: 'cold attic (outdoor air)', fakeFloor: 'fake floor', wall: 'wall', window: 'window', door: 'door', floor: 'floor', ceiling: 'ceiling', trace: 'Chain', chainMaterial: 'material', chainConstruction: 'construction', chainType: 'type',
    },
    settings: {
      title: 'Settings', building: 'Building configuration', shielding: 'Shielding class (EN 12831)', shieldingNone: 'none', shieldingModerate: 'moderate', shieldingHeavy: 'heavy', fakeFloorU: 'Fake floor U-value (W/m²K)', sliverWidth: 'Sliver: narrowest width (mm)', sliverArea: 'Sliver: minimum area (m²)', baseFlow: 'Base ventilation flow (l/s per m²)', soilTemp: 'Soil temperature for walls below grade (°C)', bandTemp: 'Slab: perimeter band (°C)', innerTemp: 'Slab: inner zone (°C)', bandWidth: 'Slab: band width (m)', soilLambda: 'Ground thermal conductivity (W/mK)', tb: 'Thermal bridge surcharge (%)', snap: 'Snap tolerance override (mm)', doorRange: 'Door height sanity range (m)', scaleNo: 'Scale: no correction below (%)', scaleAgree: 'Scale: auto-correction when walls agree within (%)', ai: 'AI settings', modelFor: 'Model for', jobs: { read: 'initial read (overview and tiles)', combined: 'combined pass per floor', fullFloorReread: 'full-floor re-read', regional: 'regional re-read on comments', annotation: 'annotations', command: 'command window' }, targetRes: 'Target resolution (mm per pixel)', overlap: 'Tile overlap (m)', tileMax: 'Max long edge per tile (px)', manual: 'Manual mode (developer setting)', workerUrl: 'Worker URL', scaleTruth: 'Scale: reference walls', wallBand: 'Wall thickness: tolerance band (mm)', openingBand: 'Openings: tolerance band (mm)', ageDefaults: 'n50 per age category', sources: 'Sources of constants', promptVersions: 'Prompt versions', clearPassword: 'Forget password', imageLimitNote: 'Model image limit at build time: 2576 px long edge, 4784 visual tokens (28 px per token).',
    },
    command: { title: 'Command window (experimental)', intro: 'Type a project-wide change. On any ambiguity the AI asks back before touching anything. Nothing changes until you click Apply.', placeholder: 'e.g. "change ground temperature to 5 °C across the project"', send: 'Send', question: 'Question back', proposal: 'Proposed changes', applied: 'Applied changes (one undo step)', freeText: 'Free text answer', history: 'History' },
    status: { saved: 'Saved', restored: 'Project restored from browser storage', calc: 'Calculated', error: 'Error' },
    roomTypes: { living: 'Living room', bedroom: 'Bedroom', kitchen: 'Kitchen', bathroom: 'Bathroom', wc: 'WC', hall: 'Hall', storage: 'Storage', stairwell: 'Stairwell', laundry: 'Laundry', office: 'Office', shop: 'Shop/premises', garage: 'Garage', loggia: 'Loggia', corridor: 'Corridor', technical: 'Technical', other: 'Other' },
    units: { mm: 'mm', m: 'm', m2: 'm²', W: 'W', C: '°C' },
  },
};

let current = 'sv';
export function setLanguage(lang) {
  current = STRINGS[lang] ? lang : 'sv';
  try {
    localStorage.setItem('kj.lang', current);
  } catch {}
}
export function getLanguage() {
  return current;
}
export function initLanguage() {
  try {
    const l = localStorage.getItem('kj.lang');
    if (l && STRINGS[l]) current = l;
  } catch {}
  return current;
}
// t('editor.title') → string in the active language; falls back to the key.
export function t(path, vars) {
  const parts = path.split('.');
  let node = STRINGS[current];
  for (const p of parts) {
    node = node && node[p];
    if (node === undefined) break;
  }
  if (node === undefined) {
    node = STRINGS.en;
    for (const p of parts) node = node && node[p];
  }
  if (typeof node !== 'string') return path;
  if (vars) return node.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? vars[k] : `{${k}}`));
  return node;
}
export const ROOM_TYPES = ['living', 'bedroom', 'kitchen', 'bathroom', 'wc', 'hall', 'storage', 'stairwell', 'laundry', 'office', 'shop', 'garage', 'loggia', 'corridor', 'technical', 'other'];
